# Generated by Django 5.2.4 on 2025-07-23 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=15)),
                ('otp', models.IntegerField(max_length=5)),
                ('verify', models.BooleanField(default=False)),
                ('otp_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
