# Generated by Django 5.2.4 on 2025-07-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='email',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='emailverify',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
